### ISSUE TITLE
Can't exit on windows with german keyboard layout

### ISSUE THREAD

**Issue by hellow554** [kumavale/sisterm#18]
Hello(w) again,

I normally use the US keyboard layout, so this doesn't bother me much, but my colleges are using a german layout and therefore this bug impacts them somewhat.

When trying to exit sisterm, the command should be <kbd>~</kbd><kbd>.</kbd>

On powershell with the US layout, this works fine:

```
[Char('~')]~[Char('.')].
Disconnected.
```

but with the german layout, this gives me:

```
[Alt('~')][Char('.')]
```

To use the <kbd>~</kbd> key, you have to press <kbd>ctrl</kbd> + <kbd>alt</kbd> + *a key next to the return key*, see:
<img src="http://www.voith-usa.com/German/Ucol/GermanCharacters/QWERTZ.jpg" />

You can also press the <kbd>AltGr</kbd> instead of <kbd>ctrl</kbd> + <kbd>alt</kbd>, but that doesn't work either.

On linux (windows terminal and wsl) it works fine and the key is properly recognized as `Char('~')`, but on windows I have this strange behavoir.

It seems to be an odd issue with `getch`? But I couldn't figure it out, sorry..

**Comment by kumavale** [comment]
Hi hellow554! Thanks for the issue.
When using a German layout keyboard, <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>~</kbd> should input the key code (126 (`Char('~')`).
However, I also confirmed that it becomes `Alt('~')`.
**It's caused by `getch`**.

I would like to ask one thing, does <kbd>Alt</kbd> + <kbd>AltGr</kbd> + <kbd>~</kbd> become `Alt('~')`?

**Comment by kumavale** [comment]
`Alt('~')` is now accepted as an escape signal. ( #19 )
I think this will work fine with a German layout keyboard, but I don't have that keyboard at hand so I can't test it.
Could you try it in @hellow554 's environment?

```
$ git clone --branch "hotfix/#18" git@github.com:kumavale/sisterm.git
$ cd sisterm
$ cargo run
```

**Comment by hellow554** [comment]
works, thanks :)

do you know what the underlying problem is? I think accepting `Alt('~')` is just a workaround for that :/

**Comment by kumavale** [comment]
In order to type <kbd>~</kbd> on a German layout keyboard, the <kbd>Alt</kbd> key is also pressed on Windows.
If you want to send `Alt('~')` to the destination, need to add a function for that to sisterm.

**Comment by hellow554** [comment]
The funny thing is that under linux (WSL) I can't reproduce the behavoir. 

> On linux (windows terminal and wsl) it works fine and the key is properly recognized as Char('~'), but on windows I have this strange behavoir.

**Comment by kumavale** [comment]
Because linux doesn't implement <kbd>Alt</kbd> key detection :(
