### ISSUE TITLE
Home, End, PageUp, PageDown keys not working properly in Powershell

### ISSUE THREAD

**Issue by hellow554** [kumavale/sisterm#2]
I'm using sisterm to connect to a linux device using a serial cable.
When I'm using a bash on the linux device, the following four keys are not working properly

<kbd>Home</kbd> produces `G`
<kbd>End</kbd> prodocues `O`
<kbd>PageUp</kbd> produces `I` (uppercase i)
<kbd>PageDown</kbd> produces `Q`

I know (I'm relatively sure) that [cursive](https://github.com/gyscos/cursive) handles such keys right with the [termion](https://crates.io/crates/termion) crate.

Would that be an option instead of the plain `_getch`?

**Comment by kumavale** [comment]
I'm sorry for replying so late and  thanks for the issue!  
I have confirmed that those keys do not work in my environment.  
It seems to work properly with the termion crate.  
Thanks for the great suggestions!!

**Comment by kumavale** [comment]
termion doesn't support Windows so I fixed the bug without using it.  
and released in v2.3.1
