### ISSUE TITLE
Another german layout problem

### ISSUE THREAD

**Issue by hellow554** [kumavale/sisterm#20]
Hey kumavale,

I still love your project and convinced a lot of my colleges to use your terminal. Thank you very much for that!

Because we are a german company, a lot of my colleges use a german keyboard layout.
Similar to #18 we have problems with characters that are accessd via the <kbd>ctrl</kbd> + <kbd>alt</kbd> ([or <kbd>AltGr</kbd>](https://en.wikipedia.org/wiki/AltGr_key)) combo, that we have a few of, e.g. `~@€{[]}|`

They all get reported as:

```
~ - [Alt('~')][27, 126]
@ - [Alt('@')][27, 64]
€ - [Alt('?')][27, 63]
{ - [Alt('{')][27, 123]
[ - [Alt('[')][27, 91]
] - [Alt(']')][27, 93]
} - [Alt('}')][27, 125]
| - [Alt('|')][27, 124]
```

As you see, they all get reported inside the `Alt(..)` enum variant. I'm not sure why windows does this, but it's an windows (powershell) exclusive problem. WSL works fine here.

Here's a list of the german keyboard AltGr keys: https://en.wikipedia.org/wiki/AltGr_key#Germany
I think the france layout will have a similar problem?

Can you take another look at this?

**Comment by kumavale** [comment]
Hello hellow554.
Thank you for reporting the bug and using `sisterm` !

The key input process on the Windows side needs to be modified.
I have split the key input processing into [getch-rs](https://github.com/kumavale/getch-rs) crates and would like to manage this problem there.

**Comment by kumavale** [comment]
@hellow554 

Fixed input process is now available. (`getch-rs` v0.1.1)
I think that reinstalling `sisterm` with the following command will work fine with German layout!

```
$ cargo install sisterm --force
```

**Comment by hellow554** [comment]
Hey kumavale.
Thanks for your response and sorry for my late-ish answer.

I installed it and it seems to work, here's the debug output of my previous inputs:

```
[Char('€')][Char('{')][Char('[')][Char(']')][Char('}')][Char('|')]
```

Does that mean we can partialy revert #19 ?

**Comment by hellow554** [comment]
Oh, one thing that's different now is that it doesn't send the keys "key by key" but instead only after I pressed enter.
Should I open a bug at getch-rs?
