### ISSUE TITLE
ctrl+arrow keys not working

### ISSUE THREAD

**Issue by hellow554** [kumavale/sisterm#4]
Thanks for the huge last update, which makes the home, end keys work.

For a better bash experience now the ctrl+arrow keys are missing (at least under windows in powershell).

**Comment by kumavale** [comment]
Thanks for the issue!  
This bug will be fixed soon.

**Comment by kumavale** [comment]
Fixed it in commit 02186165eaf82e8b8d29bdd4713725873c851a8c
