### ISSUE TITLE
Line won't get redrawn

### ISSUE THREAD

**Issue by hellow554** [kumavale/sisterm#5]
If I type a line and i use (either the arrow keys or the home key) to get to a different location in that line and start typing, the characters are overwriting the previous one, without the line to be redrawn.

This look similar to this:

![grafik](https://user-images.githubusercontent.com/921462/97146534-4c5af880-1768-11eb-960d-b03c5a351e88.png)

but should look like

![grafik](https://user-images.githubusercontent.com/921462/97146650-7f04f100-1768-11eb-8926-81846e0d92e3.png)

**Comment by kumavale** [comment]
Do you expect this kind of behavior?  

![sisterm_issue#5_1](https://user-images.githubusercontent.com/29778890/97174564-9a5a1580-17d5-11eb-9823-1488a7a1bcd2.gif)  

Works correctly on both Windows and Linux in my environment.

**Comment by hellow554** [comment]
Yes I do expect that exact behavoir you are showing in your gif.
Weird, that it doesn't work for me. 

I have a COM connection via a FTDI serial cable to a linux system. Any chance I could provide my data to you why it isn't working?

It does work in tera term for example.

**Comment by kumavale** [comment]
Could you please write the following settings in your config.toml and then provide the `ls -lha /sys/class/` data using either the arrow keys or the home key?  
```.toml
debug = true
```

**Comment by hellow554** [comment]
```
[Char('l')][108]l[Char('s')][115]s[Char(' ')][32] [Char('/')][47]/[Home][8, 8, 8[Right][108]l[Right][115]s[Char(' ')][32, 32, 47, 8, 8] [Char('-')][27, 91, 52, 104, 32, 27, 91, 52, 108, 8, 45]-[Char('l')][27, 91, 52, 104, 32, 27, 91, 52, 108, 8, 108]l[Char('h')][27, 91, 52, 104, 32, 27, 91, 52, 108, 8, 104]h[Char('a')][27, 91, 52]104, 32, 27, 91, 52, 108, 8, 97]ha[Char('\r')][13, 10]
```

this was
<kbd>l</kbd><kbd>s</kbd><kbd>&nbsp;</kbd><kbd>/</kbd><kbd>Home</kbd><kbd>→</kbd><kbd>→</kbd><kbd>&nbsp;</kbd><kbd>-</kbd><kbd>l</kbd><kbd>h</kbd><kbd>a</kbd><kbd>Enter</kbd>

**Comment by hellow554** [comment]
The home key is actually a `[8, 8, 8, 8]` but is truncated because of the home key itself?!

**Comment by hellow554** [comment]
![yoyoyo](https://user-images.githubusercontent.com/921462/97185470-61537e00-17a0-11eb-8fc5-8e28bb726ea6.gif)


Here's a gif for you ;)

**Comment by kumavale** [comment]
This is because your terminal application does not support `^[[4h` and `^[[4l`.  
This is a CSI Sequence for inserting characters: [https://ttssh2.osdn.jp/manual/4/en/about/ctrlseq.html#mode](https://ttssh2.osdn.jp/manual/4/en/about/ctrlseq.html#mode)  

### Unsupported terminal (e.g. [Windows Console](https://en.wikipedia.org/wiki/Windows_Console))
```bash
$ echo -e "abcd\x08\x08\x1b[4he\x1b[4l"
abed
```

### Supported (e.g. tera term)
```bash
$ echo -e "abcd\x08\x08\x1b[4he\x1b[4l"
abecd
```

Also, my environment doesn't support these control characters either.  
However, the following response is returned from Linux on the server side that I am using, so it is displayed correctly.  

<kbd>abcd</kbd>
```
< abcd
> abcd
---
$ abcd
```
<kbd>←</kbd><kbd>←</kbd>
```
< \x1b[D\x1b[D
> \x08\x08
---
$ abcd
```
<kbd>e</kbd>
```
< e
> ecd\x08\x08
---
$ abecd
```

## How to solve

- Use a supported terminal
- Disable Insertion/Replacement Mode (I don't know how to do it...)

**Comment by hellow554** [comment]
I'm indeed using the [windows terminal](https://aka.ms/terminal) with the powershell inside.

According to https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#cursor-positioning it does indeed support the `^[y;xH` escape sequence and inside the powershell itself, everything works finde when using the home key.

**Comment by kumavale** [comment]
`ESC[<y>;<x>H` works, but `ESC[4h` doesn't seem to work. (`H` and `h` are different)  
Could you please tell me if it is displayed correctly when using the `telnet` command from powershell.

**Comment by hellow554** [comment]
telnet doesn't work either, **but** something funny is happening (in normal mode and telnet mode)

![yoyoyo2](https://user-images.githubusercontent.com/921462/97405054-5fe89980-18f7-11eb-996b-a4a804613095.gif)

I don't know if this is a problem with the powershell as well, but when I just press the spacebar, the line gets adjusted just right, but not when typing in characters.

**Comment by kumavale** [comment]
Hmm, strange...  
Does it display properly with another command (e.g. `cu`) ?

**Comment by hellow554** [comment]
Can we do something here?

**Comment by kumavale** [comment]
sisterm is currently unwilling to support [Insertion-Replacement Mode(IRM)](https://vt100.net/docs/vt102-ug/chapter5.html#S5.5.2.22).    
If you are using Windows terminal wait for it to support IRM in [here](https://github.com/microsoft/terminal/issues/1947).

**Comment by hellow554** [comment]
FYI: It seems that the IRM PR has finally been merged: https://github.com/microsoft/terminal/commit/7813953b23c4fdf547997d4fc461802d1cb4d0ef
I will report it I get a new version of the terminal and if it changes

**Comment by hellow554** [comment]
I can confirm that from version 1.17.1023 on this is fixed.
Thanks for hinting it out :)
I still use this on a daily drive for serial communication, I love it!
